"""Add relationship to ai models

Revision ID: 3668c91fa898
Revises: 65969d0d94f3
Create Date: 2025-05-06 16:48:41.711015

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "3668c91fa898"
down_revision = "65969d0d94f3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ai_corpus", "channel", nullable=False, new_column_name="channel_name"
    )
    op.create_foreign_key(
        "fk_ai_corpus.channel_name",
        "ai_corpus",
        "ai_channels",
        ["channel_name"],
        ["name"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ai_corpus", "channel_name", nullable=False, new_column_name="channel"
    )
    op.drop_constraint("fk_ai_corpus.channel_name", "ai_corpus", type_="foreignkey")
    # ### end Alembic commands ###
