"""Rename CorpusChannel.status to CorpusChannel.enabled

Revision ID: 4dc2c5515277
Revises: a71bc86773a8
Create Date: 2025-05-06 15:53:34.642464

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "4dc2c5515277"
down_revision = "a71bc86773a8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("ai_channels", "status", nullable=False, new_column_name="enabled")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("ai_channels", "enabled", nullable=False, new_column_name="status")

    # ### end Alembic commands ###
