"""Drop chanlog and ricedb.data

Revision ID: 5ebc3fcc5af8
Revises: b99364b9b9c3
Create Date: 2025-05-06 15:42:22.244462

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5ebc3fcc5af8"
down_revision = "b99364b9b9c3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chanlog")
    op.drop_column("ricedb", "data")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ricedb",
        sa.Column(
            "data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_table(
        "chanlog",
        sa.Column("user", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("channel", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("event", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("target", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("data", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "time",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
