"""Rename Trigger.trigger to Trigger.name

Revision ID: 65969d0d94f3
Revises: 4dc2c5515277
Create Date: 2025-05-06 15:59:16.078293

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "65969d0d94f3"
down_revision = "4dc2c5515277"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("triggers", "trigger", nullable=False, new_column_name="name")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("triggers", "name", nullable=False, new_column_name="trigger")
    # ### end Alembic commands ###
