"""make ai_channels.status and ai_corpus.channel non-nullable

Revision ID: a71bc86773a8
Revises: 5ebc3fcc5af8
Create Date: 2025-05-06 15:43:59.978947

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "a71bc86773a8"
down_revision = "5ebc3fcc5af8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("ai_channels", "status", existing_type=sa.BOOLEAN(), nullable=False)
    op.alter_column("ai_corpus", "channel", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("ai_corpus", "channel", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("ai_channels", "status", existing_type=sa.BOOLEAN(), nullable=True)
    # ### end Alembic commands ###
