"""Update last_seen timestamp type

Revision ID: b99364b9b9c3
Revises: c7308e3c814a
Create Date: 2025-05-06 02:17:30.035596

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "b99364b9b9c3"
down_revision = "c7308e3c814a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "ricedb",
        "last_seen",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
    )
    op.drop_column("ricedb", "data")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ricedb",
        sa.Column(
            "data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
        ),
    )
    op.alter_column(
        "ricedb",
        "last_seen",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
    )
    # ### end Alembic commands ###
