"""empty messageTrue

Revision ID: ca58ba59b328
Revises:
Create Date: 2020-01-24 02:44:22.085585

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ca58ba59b328"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_channels",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("status", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "ai_corpus",
        sa.Column("line", sa.String(), nullable=False),
        sa.Column("channel", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("line"),
    )
    op.create_table(
        "chanlog",
        sa.Column("user", sa.String(), nullable=True),
        sa.Column("channel", sa.String(), nullable=True),
        sa.Column("event", sa.String(), nullable=True),
        sa.Column("target", sa.String(), nullable=True),
        sa.Column("data", sa.String(), nullable=True),
        sa.Column(
            "time", sa.DateTime(), server_default=sa.text("now()"), nullable=True
        ),
    )
    op.create_table(
        "ricedb",
        sa.Column("nick", sa.String(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("nick"),
    )
    op.create_table(
        "triggers",
        sa.Column("trigger", sa.String(), nullable=False),
        sa.Column("channel", sa.String(), nullable=False),
        sa.Column("response", sa.String(), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("triggers")
    op.drop_table("ricedb")
    op.drop_table("chanlog")
    op.drop_table("ai_corpus")
    op.drop_table("ai_channels")
    # ### end Alembic commands ###
