"""Delete chanlog table

Revision ID: e1915be51fb9
Revises: b99364b9b9c3
Create Date: 2025-05-06 02:20:56.584406

"""

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision = "e1915be51fb9"
down_revision = "b99364b9b9c3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("chanlog")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chanlog",
        sa.Column("user", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("channel", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("event", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("target", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("data", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "time",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
