name: cappuccino

services:
  cappuccino:
    container_name: cappuccino
    restart: "no"
    init: true
    read_only: true
    user: ${PUID:-1000}:${PGID:-1000}
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      CFG_BOT_NICK: ${CFG_BOT_NICK:?}
      CFG_BOT_REALNAME: cappuccino_dev
      CFG_BOT_USERNAME: cappuccino_dev
      CFG_IRC_HOST: ${CFG_IRC_HOST:?}
      CFG_IRC_PORT: 6697
      CFG_IRC_SSL: true
      CFG_DB_URI: postgresql://${POSTGRES_USER:-cappuccino}:${POSTGRES_PASSWORD:-cappuccino}@/${POSTGRES_DB:-cappuccino}?host=${POSTGRES_HOST:-/run/postgresql}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - postgres_socket:/run/postgresql
      - ${BASE_DIR:-.}/config/app:/config
      - ../:/app:ro
    tmpfs:
      - /tmp
    networks:
      - cappuccino
    build:
      context: ../

  db:
    image: postgres:17-alpine
    container_name: cappuccino_db
    restart: "no"
    user: ${PUID:-1000}:${PGID:-1000}
    env_file: .env
    environment:
      POSTGRES_HOST: /run/postgresql
      POSTGRES_DB: cappuccino
      POSTGRES_PASSWORD: cappuccino
      POSTGRES_USER: cappuccino
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - postgres_socket:/run/postgresql
      - ${BASE_DIR:-.}/data/postgresql:/var/lib/postgresql/data
    networks:
      - cappuccino
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -q --dbname=$$POSTGRES_DB --username=$$POSTGRES_USER --host=$$POSTGRES_HOST",
        ]
      start_period: 5s
      start_interval: 1s
      interval: 10s
      timeout: 1s

volumes:
  postgres_socket:

networks:
  cappuccino:
