name: cappuccino

services:
  cappuccino:
    container_name: cappuccino
    restart: "no"
    init: true
    read_only: true
    user: ${PUID:-1000}:${PGID:-1000}
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      CFG_BOT_NICK: ${CFG_BOT_NICK:?}
      CFG_BOT_REALNAME: cappuccino_dev
      CFG_BOT_USERNAME: cappuccino_dev
      CFG_IRC_HOST: ${CFG_IRC_HOST:?}
      CFG_IRC_PORT: 6697
      CFG_IRC_SSL: true
      CFG_DB_URI: postgresql://${POSTGRES_USER:-cappuccino}:${POSTGRES_PASSWORD:-cappuccino}@${POSTGRES_HOST:-db}/${POSTGRES_DB:-cappuccino}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:-.}/config/app:/config
      - ../cappuccino:/app/cappuccino
    tmpfs:
      - /tmp
    networks:
      - cappuccino
    build:
      context: ../
    deploy:
      resources:
        limits:
          cpus: ${CAPPUCCINO_CPU_LIMIT:-${CPU_LIMIT:-0}}
          memory: ${CAPPUCCINO_MEM_LIMIT:-${MEM_LIMIT:-0}}

  db:
    image: postgres:17-alpine
    container_name: cappuccino_db
    restart: "no"
    init: true
    user: ${PUID:-1000}:${PGID:-1000}
    env_file: .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: cappuccino
      POSTGRES_PASSWORD: cappuccino
      POSTGRES_USER: cappuccino
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${BASE_DIR:-.}/data/postgresql:/var/lib/postgresql/data
    networks:
      - cappuccino
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -q --dbname=$$POSTGRES_DB --username=$$POSTGRES_USER --host=$$POSTGRES_HOST",
        ]
      start_period: 5s
      start_interval: 1s
      interval: 10s
      timeout: 1s
    deploy:
      resources:
        limits:
          cpus: ${POSTGRES_CPU_LIMIT:-${CPU_LIMIT:-0}}
          memory: ${POSTGRES_MEM_LIMIT:-${MEM_LIMIT:-0}}

networks:
  cappuccino:
